//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseño_UI.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long id_tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long id_presentacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatatipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataPresentacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long id_tipo {
            get {
                return this.id_tipoField;
            }
            set {
                if ((this.id_tipoField.Equals(value) != true)) {
                    this.id_tipoField = value;
                    this.RaisePropertyChanged("id_tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long id_presentacion {
            get {
                return this.id_presentacionField;
            }
            set {
                if ((this.id_presentacionField.Equals(value) != true)) {
                    this.id_presentacionField = value;
                    this.RaisePropertyChanged("id_presentacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Datatipo {
            get {
                return this.DatatipoField;
            }
            set {
                if ((object.ReferenceEquals(this.DatatipoField, value) != true)) {
                    this.DatatipoField = value;
                    this.RaisePropertyChanged("Datatipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string DataPresentacion {
            get {
                return this.DataPresentacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DataPresentacionField, value) != true)) {
                    this.DataPresentacionField = value;
                    this.RaisePropertyChanged("DataPresentacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inventariob", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class Inventariob : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long id_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long id_proveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_eField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] imagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatasexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_producto {
            get {
                return this.id_productoField;
            }
            set {
                if ((this.id_productoField.Equals(value) != true)) {
                    this.id_productoField = value;
                    this.RaisePropertyChanged("id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long id_proveedor {
            get {
                return this.id_proveedorField;
            }
            set {
                if ((this.id_proveedorField.Equals(value) != true)) {
                    this.id_proveedorField = value;
                    this.RaisePropertyChanged("id_proveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int id_sexo {
            get {
                return this.id_sexoField;
            }
            set {
                if ((this.id_sexoField.Equals(value) != true)) {
                    this.id_sexoField = value;
                    this.RaisePropertyChanged("id_sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string fecha_e {
            get {
                return this.fecha_eField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_eField, value) != true)) {
                    this.fecha_eField = value;
                    this.RaisePropertyChanged("fecha_e");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public byte[] imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string DataProducto {
            get {
                return this.DataProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataProductoField, value) != true)) {
                    this.DataProductoField = value;
                    this.RaisePropertyChanged("DataProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string DataProveedor {
            get {
                return this.DataProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.DataProveedorField, value) != true)) {
                    this.DataProveedorField = value;
                    this.RaisePropertyChanged("DataProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Datasexo {
            get {
                return this.DatasexoField;
            }
            set {
                if ((object.ReferenceEquals(this.DatasexoField, value) != true)) {
                    this.DatasexoField = value;
                    this.RaisePropertyChanged("Datasexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tipo", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class tipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="presentacion", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class presentacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="proveedor", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string contacto {
            get {
                return this.contactoField;
            }
            set {
                if ((object.ReferenceEquals(this.contactoField, value) != true)) {
                    this.contactoField = value;
                    this.RaisePropertyChanged("contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string direcion {
            get {
                return this.direcionField;
            }
            set {
                if ((object.ReferenceEquals(this.direcionField, value) != true)) {
                    this.direcionField = value;
                    this.RaisePropertyChanged("direcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] imagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatasexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((this.sexoField.Equals(value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseñaField, value) != true)) {
                    this.contraseñaField = value;
                    this.RaisePropertyChanged("contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public byte[] imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Datasexo {
            get {
                return this.DatasexoField;
            }
            set {
                if ((object.ReferenceEquals(this.DatasexoField, value) != true)) {
                    this.DatasexoField = value;
                    this.RaisePropertyChanged("Datasexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sexo", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class sexo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cargo", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class cargo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int duiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_nField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datasexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datacargoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((this.sexoField.Equals(value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int dui {
            get {
                return this.duiField;
            }
            set {
                if ((this.duiField.Equals(value) != true)) {
                    this.duiField = value;
                    this.RaisePropertyChanged("dui");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime fecha_n {
            get {
                return this.fecha_nField;
            }
            set {
                if ((this.fecha_nField.Equals(value) != true)) {
                    this.fecha_nField = value;
                    this.RaisePropertyChanged("fecha_n");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int cargo {
            get {
                return this.cargoField;
            }
            set {
                if ((this.cargoField.Equals(value) != true)) {
                    this.cargoField = value;
                    this.RaisePropertyChanged("cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string nick {
            get {
                return this.nickField;
            }
            set {
                if ((object.ReferenceEquals(this.nickField, value) != true)) {
                    this.nickField = value;
                    this.RaisePropertyChanged("nick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string datasexo {
            get {
                return this.datasexoField;
            }
            set {
                if ((object.ReferenceEquals(this.datasexoField, value) != true)) {
                    this.datasexoField = value;
                    this.RaisePropertyChanged("datasexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string datacargo {
            get {
                return this.datacargoField;
            }
            set {
                if ((object.ReferenceEquals(this.datacargoField, value) != true)) {
                    this.datacargoField = value;
                    this.RaisePropertyChanged("datacargo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ventas", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class ventas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long id_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long id_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_producto {
            get {
                return this.id_productoField;
            }
            set {
                if ((this.id_productoField.Equals(value) != true)) {
                    this.id_productoField = value;
                    this.RaisePropertyChanged("id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                if ((this.id_usuarioField.Equals(value) != true)) {
                    this.id_usuarioField = value;
                    this.RaisePropertyChanged("id_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_producto", ReplyAction="http://tempuri.org/IService1/agregar_productoResponse")]
        int agregar_producto(Diseño_UI.ServiceReference.Producto pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_producto", ReplyAction="http://tempuri.org/IService1/agregar_productoResponse")]
        System.Threading.Tasks.Task<int> agregar_productoAsync(Diseño_UI.ServiceReference.Producto pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_producto", ReplyAction="http://tempuri.org/IService1/actualizar_productoResponse")]
        int actualizar_producto(Diseño_UI.ServiceReference.Producto pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_producto", ReplyAction="http://tempuri.org/IService1/actualizar_productoResponse")]
        System.Threading.Tasks.Task<int> actualizar_productoAsync(Diseño_UI.ServiceReference.Producto pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_producto", ReplyAction="http://tempuri.org/IService1/eliminar_productoResponse")]
        int eliminar_producto(Diseño_UI.ServiceReference.Producto pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_producto", ReplyAction="http://tempuri.org/IService1/eliminar_productoResponse")]
        System.Threading.Tasks.Task<int> eliminar_productoAsync(Diseño_UI.ServiceReference.Producto pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_producto", ReplyAction="http://tempuri.org/IService1/mostrar_productoResponse")]
        Diseño_UI.ServiceReference.Producto[] mostrar_producto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_producto", ReplyAction="http://tempuri.org/IService1/mostrar_productoResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Producto[]> mostrar_productoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar_producto", ReplyAction="http://tempuri.org/IService1/buscar_productoResponse")]
        Diseño_UI.ServiceReference.Producto[] buscar_producto(Diseño_UI.ServiceReference.Producto pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar_producto", ReplyAction="http://tempuri.org/IService1/buscar_productoResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Producto[]> buscar_productoAsync(Diseño_UI.ServiceReference.Producto pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_inventario", ReplyAction="http://tempuri.org/IService1/agregar_inventarioResponse")]
        int agregar_inventario(Diseño_UI.ServiceReference.Inventariob pen3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_inventario", ReplyAction="http://tempuri.org/IService1/agregar_inventarioResponse")]
        System.Threading.Tasks.Task<int> agregar_inventarioAsync(Diseño_UI.ServiceReference.Inventariob pen3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_inventario", ReplyAction="http://tempuri.org/IService1/actualizar_inventarioResponse")]
        int actualizar_inventario(Diseño_UI.ServiceReference.Inventariob pen3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_inventario", ReplyAction="http://tempuri.org/IService1/actualizar_inventarioResponse")]
        System.Threading.Tasks.Task<int> actualizar_inventarioAsync(Diseño_UI.ServiceReference.Inventariob pen3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_inventario", ReplyAction="http://tempuri.org/IService1/eliminar_inventarioResponse")]
        int eliminar_inventario(Diseño_UI.ServiceReference.Inventariob pen3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_inventario", ReplyAction="http://tempuri.org/IService1/eliminar_inventarioResponse")]
        System.Threading.Tasks.Task<int> eliminar_inventarioAsync(Diseño_UI.ServiceReference.Inventariob pen3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_inventario", ReplyAction="http://tempuri.org/IService1/mostrar_inventarioResponse")]
        Diseño_UI.ServiceReference.Inventariob[] mostrar_inventario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_inventario", ReplyAction="http://tempuri.org/IService1/mostrar_inventarioResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob[]> mostrar_inventarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar_inventario", ReplyAction="http://tempuri.org/IService1/buscar_inventarioResponse")]
        Diseño_UI.ServiceReference.Inventariob[] buscar_inventario(Diseño_UI.ServiceReference.Inventariob pen3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar_inventario", ReplyAction="http://tempuri.org/IService1/buscar_inventarioResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob[]> buscar_inventarioAsync(Diseño_UI.ServiceReference.Inventariob pen3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_inventartio_id", ReplyAction="http://tempuri.org/IService1/mostrar_inventartio_idResponse")]
        Diseño_UI.ServiceReference.Inventariob[] mostrar_inventartio_id(long pen3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_inventartio_id", ReplyAction="http://tempuri.org/IService1/mostrar_inventartio_idResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob[]> mostrar_inventartio_idAsync(long pen3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Listar_Productos_carrito", ReplyAction="http://tempuri.org/IService1/Listar_Productos_carritoResponse")]
        Diseño_UI.ServiceReference.Inventariob Listar_Productos_carrito(long pen3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Listar_Productos_carrito", ReplyAction="http://tempuri.org/IService1/Listar_Productos_carritoResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob> Listar_Productos_carritoAsync(long pen3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_inventario_mujeres", ReplyAction="http://tempuri.org/IService1/mostrar_inventario_mujeresResponse")]
        Diseño_UI.ServiceReference.Inventariob[] mostrar_inventario_mujeres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_inventario_mujeres", ReplyAction="http://tempuri.org/IService1/mostrar_inventario_mujeresResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob[]> mostrar_inventario_mujeresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_inventario_hombres", ReplyAction="http://tempuri.org/IService1/mostrar_inventario_hombresResponse")]
        Diseño_UI.ServiceReference.Inventariob[] mostrar_inventario_hombres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_inventario_hombres", ReplyAction="http://tempuri.org/IService1/mostrar_inventario_hombresResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob[]> mostrar_inventario_hombresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ventas_top", ReplyAction="http://tempuri.org/IService1/ventas_topResponse")]
        Diseño_UI.ServiceReference.Inventariob[] ventas_top();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ventas_top", ReplyAction="http://tempuri.org/IService1/ventas_topResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob[]> ventas_topAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_tipo", ReplyAction="http://tempuri.org/IService1/agregar_tipoResponse")]
        int agregar_tipo(Diseño_UI.ServiceReference.tipo pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_tipo", ReplyAction="http://tempuri.org/IService1/agregar_tipoResponse")]
        System.Threading.Tasks.Task<int> agregar_tipoAsync(Diseño_UI.ServiceReference.tipo pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_tipo", ReplyAction="http://tempuri.org/IService1/mostrar_tipoResponse")]
        Diseño_UI.ServiceReference.tipo[] mostrar_tipo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_tipo", ReplyAction="http://tempuri.org/IService1/mostrar_tipoResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.tipo[]> mostrar_tipoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_tipo", ReplyAction="http://tempuri.org/IService1/actualizar_tipoResponse")]
        int actualizar_tipo(Diseño_UI.ServiceReference.tipo pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_tipo", ReplyAction="http://tempuri.org/IService1/actualizar_tipoResponse")]
        System.Threading.Tasks.Task<int> actualizar_tipoAsync(Diseño_UI.ServiceReference.tipo pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_tipo", ReplyAction="http://tempuri.org/IService1/eliminar_tipoResponse")]
        int eliminar_tipo(Diseño_UI.ServiceReference.tipo pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_tipo", ReplyAction="http://tempuri.org/IService1/eliminar_tipoResponse")]
        System.Threading.Tasks.Task<int> eliminar_tipoAsync(Diseño_UI.ServiceReference.tipo pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar_tipo", ReplyAction="http://tempuri.org/IService1/buscar_tipoResponse")]
        Diseño_UI.ServiceReference.tipo[] buscar_tipo(Diseño_UI.ServiceReference.tipo pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar_tipo", ReplyAction="http://tempuri.org/IService1/buscar_tipoResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.tipo[]> buscar_tipoAsync(Diseño_UI.ServiceReference.tipo pen4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_presentacion", ReplyAction="http://tempuri.org/IService1/agregar_presentacionResponse")]
        int agregar_presentacion(Diseño_UI.ServiceReference.presentacion pen5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_presentacion", ReplyAction="http://tempuri.org/IService1/agregar_presentacionResponse")]
        System.Threading.Tasks.Task<int> agregar_presentacionAsync(Diseño_UI.ServiceReference.presentacion pen5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_presentacion", ReplyAction="http://tempuri.org/IService1/mostrar_presentacionResponse")]
        Diseño_UI.ServiceReference.presentacion[] mostrar_presentacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_presentacion", ReplyAction="http://tempuri.org/IService1/mostrar_presentacionResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.presentacion[]> mostrar_presentacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_presentacion", ReplyAction="http://tempuri.org/IService1/actualizar_presentacionResponse")]
        int actualizar_presentacion(Diseño_UI.ServiceReference.presentacion pen5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_presentacion", ReplyAction="http://tempuri.org/IService1/actualizar_presentacionResponse")]
        System.Threading.Tasks.Task<int> actualizar_presentacionAsync(Diseño_UI.ServiceReference.presentacion pen5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_presentacion", ReplyAction="http://tempuri.org/IService1/eliminar_presentacionResponse")]
        int eliminar_presentacion(Diseño_UI.ServiceReference.presentacion pen5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_presentacion", ReplyAction="http://tempuri.org/IService1/eliminar_presentacionResponse")]
        System.Threading.Tasks.Task<int> eliminar_presentacionAsync(Diseño_UI.ServiceReference.presentacion pen5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar_presentacion", ReplyAction="http://tempuri.org/IService1/buscar_presentacionResponse")]
        Diseño_UI.ServiceReference.presentacion[] buscar_presentacion(Diseño_UI.ServiceReference.presentacion pen5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar_presentacion", ReplyAction="http://tempuri.org/IService1/buscar_presentacionResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.presentacion[]> buscar_presentacionAsync(Diseño_UI.ServiceReference.presentacion pen5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_proveedor", ReplyAction="http://tempuri.org/IService1/agregar_proveedorResponse")]
        int agregar_proveedor(Diseño_UI.ServiceReference.proveedor pen6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_proveedor", ReplyAction="http://tempuri.org/IService1/agregar_proveedorResponse")]
        System.Threading.Tasks.Task<int> agregar_proveedorAsync(Diseño_UI.ServiceReference.proveedor pen6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_proveedor", ReplyAction="http://tempuri.org/IService1/actualizar_proveedorResponse")]
        int actualizar_proveedor(Diseño_UI.ServiceReference.proveedor pen6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_proveedor", ReplyAction="http://tempuri.org/IService1/actualizar_proveedorResponse")]
        System.Threading.Tasks.Task<int> actualizar_proveedorAsync(Diseño_UI.ServiceReference.proveedor pen6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_proveedor", ReplyAction="http://tempuri.org/IService1/eliminar_proveedorResponse")]
        int eliminar_proveedor(Diseño_UI.ServiceReference.proveedor pen6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_proveedor", ReplyAction="http://tempuri.org/IService1/eliminar_proveedorResponse")]
        System.Threading.Tasks.Task<int> eliminar_proveedorAsync(Diseño_UI.ServiceReference.proveedor pen6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_proveedor", ReplyAction="http://tempuri.org/IService1/mostrar_proveedorResponse")]
        Diseño_UI.ServiceReference.proveedor[] mostrar_proveedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_proveedor", ReplyAction="http://tempuri.org/IService1/mostrar_proveedorResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.proveedor[]> mostrar_proveedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar_proveedor", ReplyAction="http://tempuri.org/IService1/buscar_proveedorResponse")]
        Diseño_UI.ServiceReference.proveedor[] buscar_proveedor(Diseño_UI.ServiceReference.proveedor pen6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar_proveedor", ReplyAction="http://tempuri.org/IService1/buscar_proveedorResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.proveedor[]> buscar_proveedorAsync(Diseño_UI.ServiceReference.proveedor pen6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_usuario", ReplyAction="http://tempuri.org/IService1/agregar_usuarioResponse")]
        int agregar_usuario(Diseño_UI.ServiceReference.Usuario pen7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_usuario", ReplyAction="http://tempuri.org/IService1/agregar_usuarioResponse")]
        System.Threading.Tasks.Task<int> agregar_usuarioAsync(Diseño_UI.ServiceReference.Usuario pen7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_usuario", ReplyAction="http://tempuri.org/IService1/eliminar_usuarioResponse")]
        int eliminar_usuario(Diseño_UI.ServiceReference.Usuario pen7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_usuario", ReplyAction="http://tempuri.org/IService1/eliminar_usuarioResponse")]
        System.Threading.Tasks.Task<int> eliminar_usuarioAsync(Diseño_UI.ServiceReference.Usuario pen7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validar_usuario", ReplyAction="http://tempuri.org/IService1/validar_usuarioResponse")]
        int validar_usuario(Diseño_UI.ServiceReference.Usuario pen7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validar_usuario", ReplyAction="http://tempuri.org/IService1/validar_usuarioResponse")]
        System.Threading.Tasks.Task<int> validar_usuarioAsync(Diseño_UI.ServiceReference.Usuario pen7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_usuario_correo", ReplyAction="http://tempuri.org/IService1/mostrar_usuario_correoResponse")]
        Diseño_UI.ServiceReference.Usuario[] mostrar_usuario_correo(Diseño_UI.ServiceReference.Usuario pen7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_usuario_correo", ReplyAction="http://tempuri.org/IService1/mostrar_usuario_correoResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Usuario[]> mostrar_usuario_correoAsync(Diseño_UI.ServiceReference.Usuario pen7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_usuario_id", ReplyAction="http://tempuri.org/IService1/mostrar_usuario_idResponse")]
        Diseño_UI.ServiceReference.Usuario[] mostrar_usuario_id(long pen7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_usuario_id", ReplyAction="http://tempuri.org/IService1/mostrar_usuario_idResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Usuario[]> mostrar_usuario_idAsync(long pen7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_usuario", ReplyAction="http://tempuri.org/IService1/actualizar_usuarioResponse")]
        int actualizar_usuario(Diseño_UI.ServiceReference.Usuario pen7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_usuario", ReplyAction="http://tempuri.org/IService1/actualizar_usuarioResponse")]
        System.Threading.Tasks.Task<int> actualizar_usuarioAsync(Diseño_UI.ServiceReference.Usuario pen7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_sexo", ReplyAction="http://tempuri.org/IService1/agregar_sexoResponse")]
        int agregar_sexo(Diseño_UI.ServiceReference.sexo pen8);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_sexo", ReplyAction="http://tempuri.org/IService1/agregar_sexoResponse")]
        System.Threading.Tasks.Task<int> agregar_sexoAsync(Diseño_UI.ServiceReference.sexo pen8);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_sexo", ReplyAction="http://tempuri.org/IService1/mostrar_sexoResponse")]
        Diseño_UI.ServiceReference.sexo[] mostrar_sexo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_sexo", ReplyAction="http://tempuri.org/IService1/mostrar_sexoResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.sexo[]> mostrar_sexoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_cargo", ReplyAction="http://tempuri.org/IService1/agregar_cargoResponse")]
        int agregar_cargo(Diseño_UI.ServiceReference.cargo pen9);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_cargo", ReplyAction="http://tempuri.org/IService1/agregar_cargoResponse")]
        System.Threading.Tasks.Task<int> agregar_cargoAsync(Diseño_UI.ServiceReference.cargo pen9);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_cargo", ReplyAction="http://tempuri.org/IService1/mostrar_cargoResponse")]
        Diseño_UI.ServiceReference.cargo[] mostrar_cargo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_cargo", ReplyAction="http://tempuri.org/IService1/mostrar_cargoResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.cargo[]> mostrar_cargoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_empleado", ReplyAction="http://tempuri.org/IService1/agregar_empleadoResponse")]
        int agregar_empleado(Diseño_UI.ServiceReference.Empleado pen10);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_empleado", ReplyAction="http://tempuri.org/IService1/agregar_empleadoResponse")]
        System.Threading.Tasks.Task<int> agregar_empleadoAsync(Diseño_UI.ServiceReference.Empleado pen10);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_empleado", ReplyAction="http://tempuri.org/IService1/actualizar_empleadoResponse")]
        int actualizar_empleado(Diseño_UI.ServiceReference.Empleado pen10);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actualizar_empleado", ReplyAction="http://tempuri.org/IService1/actualizar_empleadoResponse")]
        System.Threading.Tasks.Task<int> actualizar_empleadoAsync(Diseño_UI.ServiceReference.Empleado pen10);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_empleado", ReplyAction="http://tempuri.org/IService1/eliminar_empleadoResponse")]
        int eliminar_empleado(Diseño_UI.ServiceReference.Empleado pen10);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar_empleado", ReplyAction="http://tempuri.org/IService1/eliminar_empleadoResponse")]
        System.Threading.Tasks.Task<int> eliminar_empleadoAsync(Diseño_UI.ServiceReference.Empleado pen10);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_empleado", ReplyAction="http://tempuri.org/IService1/mostrar_empleadoResponse")]
        Diseño_UI.ServiceReference.Empleado[] mostrar_empleado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_empleado", ReplyAction="http://tempuri.org/IService1/mostrar_empleadoResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Empleado[]> mostrar_empleadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validar_empleado", ReplyAction="http://tempuri.org/IService1/validar_empleadoResponse")]
        int validar_empleado(Diseño_UI.ServiceReference.Empleado pen10);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validar_empleado", ReplyAction="http://tempuri.org/IService1/validar_empleadoResponse")]
        System.Threading.Tasks.Task<int> validar_empleadoAsync(Diseño_UI.ServiceReference.Empleado pen10);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_ventas", ReplyAction="http://tempuri.org/IService1/agregar_ventasResponse")]
        int agregar_ventas(Diseño_UI.ServiceReference.ventas pen11);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregar_ventas", ReplyAction="http://tempuri.org/IService1/agregar_ventasResponse")]
        System.Threading.Tasks.Task<int> agregar_ventasAsync(Diseño_UI.ServiceReference.ventas pen11);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_ventas", ReplyAction="http://tempuri.org/IService1/mostrar_ventasResponse")]
        Diseño_UI.ServiceReference.ventas[] mostrar_ventas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mostrar_ventas", ReplyAction="http://tempuri.org/IService1/mostrar_ventasResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.ventas[]> mostrar_ventasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar_ventas", ReplyAction="http://tempuri.org/IService1/buscar_ventasResponse")]
        Diseño_UI.ServiceReference.ventas[] buscar_ventas(Diseño_UI.ServiceReference.ventas pen11);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscar_ventas", ReplyAction="http://tempuri.org/IService1/buscar_ventasResponse")]
        System.Threading.Tasks.Task<Diseño_UI.ServiceReference.ventas[]> buscar_ventasAsync(Diseño_UI.ServiceReference.ventas pen11);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Diseño_UI.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Diseño_UI.ServiceReference.IService1>, Diseño_UI.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int agregar_producto(Diseño_UI.ServiceReference.Producto pen4) {
            return base.Channel.agregar_producto(pen4);
        }
        
        public System.Threading.Tasks.Task<int> agregar_productoAsync(Diseño_UI.ServiceReference.Producto pen4) {
            return base.Channel.agregar_productoAsync(pen4);
        }
        
        public int actualizar_producto(Diseño_UI.ServiceReference.Producto pen4) {
            return base.Channel.actualizar_producto(pen4);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_productoAsync(Diseño_UI.ServiceReference.Producto pen4) {
            return base.Channel.actualizar_productoAsync(pen4);
        }
        
        public int eliminar_producto(Diseño_UI.ServiceReference.Producto pen4) {
            return base.Channel.eliminar_producto(pen4);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_productoAsync(Diseño_UI.ServiceReference.Producto pen4) {
            return base.Channel.eliminar_productoAsync(pen4);
        }
        
        public Diseño_UI.ServiceReference.Producto[] mostrar_producto() {
            return base.Channel.mostrar_producto();
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Producto[]> mostrar_productoAsync() {
            return base.Channel.mostrar_productoAsync();
        }
        
        public Diseño_UI.ServiceReference.Producto[] buscar_producto(Diseño_UI.ServiceReference.Producto pen4) {
            return base.Channel.buscar_producto(pen4);
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Producto[]> buscar_productoAsync(Diseño_UI.ServiceReference.Producto pen4) {
            return base.Channel.buscar_productoAsync(pen4);
        }
        
        public int agregar_inventario(Diseño_UI.ServiceReference.Inventariob pen3) {
            return base.Channel.agregar_inventario(pen3);
        }
        
        public System.Threading.Tasks.Task<int> agregar_inventarioAsync(Diseño_UI.ServiceReference.Inventariob pen3) {
            return base.Channel.agregar_inventarioAsync(pen3);
        }
        
        public int actualizar_inventario(Diseño_UI.ServiceReference.Inventariob pen3) {
            return base.Channel.actualizar_inventario(pen3);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_inventarioAsync(Diseño_UI.ServiceReference.Inventariob pen3) {
            return base.Channel.actualizar_inventarioAsync(pen3);
        }
        
        public int eliminar_inventario(Diseño_UI.ServiceReference.Inventariob pen3) {
            return base.Channel.eliminar_inventario(pen3);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_inventarioAsync(Diseño_UI.ServiceReference.Inventariob pen3) {
            return base.Channel.eliminar_inventarioAsync(pen3);
        }
        
        public Diseño_UI.ServiceReference.Inventariob[] mostrar_inventario() {
            return base.Channel.mostrar_inventario();
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob[]> mostrar_inventarioAsync() {
            return base.Channel.mostrar_inventarioAsync();
        }
        
        public Diseño_UI.ServiceReference.Inventariob[] buscar_inventario(Diseño_UI.ServiceReference.Inventariob pen3) {
            return base.Channel.buscar_inventario(pen3);
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob[]> buscar_inventarioAsync(Diseño_UI.ServiceReference.Inventariob pen3) {
            return base.Channel.buscar_inventarioAsync(pen3);
        }
        
        public Diseño_UI.ServiceReference.Inventariob[] mostrar_inventartio_id(long pen3) {
            return base.Channel.mostrar_inventartio_id(pen3);
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob[]> mostrar_inventartio_idAsync(long pen3) {
            return base.Channel.mostrar_inventartio_idAsync(pen3);
        }
        
        public Diseño_UI.ServiceReference.Inventariob Listar_Productos_carrito(long pen3) {
            return base.Channel.Listar_Productos_carrito(pen3);
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob> Listar_Productos_carritoAsync(long pen3) {
            return base.Channel.Listar_Productos_carritoAsync(pen3);
        }
        
        public Diseño_UI.ServiceReference.Inventariob[] mostrar_inventario_mujeres() {
            return base.Channel.mostrar_inventario_mujeres();
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob[]> mostrar_inventario_mujeresAsync() {
            return base.Channel.mostrar_inventario_mujeresAsync();
        }
        
        public Diseño_UI.ServiceReference.Inventariob[] mostrar_inventario_hombres() {
            return base.Channel.mostrar_inventario_hombres();
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob[]> mostrar_inventario_hombresAsync() {
            return base.Channel.mostrar_inventario_hombresAsync();
        }
        
        public Diseño_UI.ServiceReference.Inventariob[] ventas_top() {
            return base.Channel.ventas_top();
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Inventariob[]> ventas_topAsync() {
            return base.Channel.ventas_topAsync();
        }
        
        public int agregar_tipo(Diseño_UI.ServiceReference.tipo pen4) {
            return base.Channel.agregar_tipo(pen4);
        }
        
        public System.Threading.Tasks.Task<int> agregar_tipoAsync(Diseño_UI.ServiceReference.tipo pen4) {
            return base.Channel.agregar_tipoAsync(pen4);
        }
        
        public Diseño_UI.ServiceReference.tipo[] mostrar_tipo() {
            return base.Channel.mostrar_tipo();
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.tipo[]> mostrar_tipoAsync() {
            return base.Channel.mostrar_tipoAsync();
        }
        
        public int actualizar_tipo(Diseño_UI.ServiceReference.tipo pen4) {
            return base.Channel.actualizar_tipo(pen4);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_tipoAsync(Diseño_UI.ServiceReference.tipo pen4) {
            return base.Channel.actualizar_tipoAsync(pen4);
        }
        
        public int eliminar_tipo(Diseño_UI.ServiceReference.tipo pen4) {
            return base.Channel.eliminar_tipo(pen4);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_tipoAsync(Diseño_UI.ServiceReference.tipo pen4) {
            return base.Channel.eliminar_tipoAsync(pen4);
        }
        
        public Diseño_UI.ServiceReference.tipo[] buscar_tipo(Diseño_UI.ServiceReference.tipo pen4) {
            return base.Channel.buscar_tipo(pen4);
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.tipo[]> buscar_tipoAsync(Diseño_UI.ServiceReference.tipo pen4) {
            return base.Channel.buscar_tipoAsync(pen4);
        }
        
        public int agregar_presentacion(Diseño_UI.ServiceReference.presentacion pen5) {
            return base.Channel.agregar_presentacion(pen5);
        }
        
        public System.Threading.Tasks.Task<int> agregar_presentacionAsync(Diseño_UI.ServiceReference.presentacion pen5) {
            return base.Channel.agregar_presentacionAsync(pen5);
        }
        
        public Diseño_UI.ServiceReference.presentacion[] mostrar_presentacion() {
            return base.Channel.mostrar_presentacion();
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.presentacion[]> mostrar_presentacionAsync() {
            return base.Channel.mostrar_presentacionAsync();
        }
        
        public int actualizar_presentacion(Diseño_UI.ServiceReference.presentacion pen5) {
            return base.Channel.actualizar_presentacion(pen5);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_presentacionAsync(Diseño_UI.ServiceReference.presentacion pen5) {
            return base.Channel.actualizar_presentacionAsync(pen5);
        }
        
        public int eliminar_presentacion(Diseño_UI.ServiceReference.presentacion pen5) {
            return base.Channel.eliminar_presentacion(pen5);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_presentacionAsync(Diseño_UI.ServiceReference.presentacion pen5) {
            return base.Channel.eliminar_presentacionAsync(pen5);
        }
        
        public Diseño_UI.ServiceReference.presentacion[] buscar_presentacion(Diseño_UI.ServiceReference.presentacion pen5) {
            return base.Channel.buscar_presentacion(pen5);
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.presentacion[]> buscar_presentacionAsync(Diseño_UI.ServiceReference.presentacion pen5) {
            return base.Channel.buscar_presentacionAsync(pen5);
        }
        
        public int agregar_proveedor(Diseño_UI.ServiceReference.proveedor pen6) {
            return base.Channel.agregar_proveedor(pen6);
        }
        
        public System.Threading.Tasks.Task<int> agregar_proveedorAsync(Diseño_UI.ServiceReference.proveedor pen6) {
            return base.Channel.agregar_proveedorAsync(pen6);
        }
        
        public int actualizar_proveedor(Diseño_UI.ServiceReference.proveedor pen6) {
            return base.Channel.actualizar_proveedor(pen6);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_proveedorAsync(Diseño_UI.ServiceReference.proveedor pen6) {
            return base.Channel.actualizar_proveedorAsync(pen6);
        }
        
        public int eliminar_proveedor(Diseño_UI.ServiceReference.proveedor pen6) {
            return base.Channel.eliminar_proveedor(pen6);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_proveedorAsync(Diseño_UI.ServiceReference.proveedor pen6) {
            return base.Channel.eliminar_proveedorAsync(pen6);
        }
        
        public Diseño_UI.ServiceReference.proveedor[] mostrar_proveedor() {
            return base.Channel.mostrar_proveedor();
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.proveedor[]> mostrar_proveedorAsync() {
            return base.Channel.mostrar_proveedorAsync();
        }
        
        public Diseño_UI.ServiceReference.proveedor[] buscar_proveedor(Diseño_UI.ServiceReference.proveedor pen6) {
            return base.Channel.buscar_proveedor(pen6);
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.proveedor[]> buscar_proveedorAsync(Diseño_UI.ServiceReference.proveedor pen6) {
            return base.Channel.buscar_proveedorAsync(pen6);
        }
        
        public int agregar_usuario(Diseño_UI.ServiceReference.Usuario pen7) {
            return base.Channel.agregar_usuario(pen7);
        }
        
        public System.Threading.Tasks.Task<int> agregar_usuarioAsync(Diseño_UI.ServiceReference.Usuario pen7) {
            return base.Channel.agregar_usuarioAsync(pen7);
        }
        
        public int eliminar_usuario(Diseño_UI.ServiceReference.Usuario pen7) {
            return base.Channel.eliminar_usuario(pen7);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_usuarioAsync(Diseño_UI.ServiceReference.Usuario pen7) {
            return base.Channel.eliminar_usuarioAsync(pen7);
        }
        
        public int validar_usuario(Diseño_UI.ServiceReference.Usuario pen7) {
            return base.Channel.validar_usuario(pen7);
        }
        
        public System.Threading.Tasks.Task<int> validar_usuarioAsync(Diseño_UI.ServiceReference.Usuario pen7) {
            return base.Channel.validar_usuarioAsync(pen7);
        }
        
        public Diseño_UI.ServiceReference.Usuario[] mostrar_usuario_correo(Diseño_UI.ServiceReference.Usuario pen7) {
            return base.Channel.mostrar_usuario_correo(pen7);
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Usuario[]> mostrar_usuario_correoAsync(Diseño_UI.ServiceReference.Usuario pen7) {
            return base.Channel.mostrar_usuario_correoAsync(pen7);
        }
        
        public Diseño_UI.ServiceReference.Usuario[] mostrar_usuario_id(long pen7) {
            return base.Channel.mostrar_usuario_id(pen7);
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Usuario[]> mostrar_usuario_idAsync(long pen7) {
            return base.Channel.mostrar_usuario_idAsync(pen7);
        }
        
        public int actualizar_usuario(Diseño_UI.ServiceReference.Usuario pen7) {
            return base.Channel.actualizar_usuario(pen7);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_usuarioAsync(Diseño_UI.ServiceReference.Usuario pen7) {
            return base.Channel.actualizar_usuarioAsync(pen7);
        }
        
        public int agregar_sexo(Diseño_UI.ServiceReference.sexo pen8) {
            return base.Channel.agregar_sexo(pen8);
        }
        
        public System.Threading.Tasks.Task<int> agregar_sexoAsync(Diseño_UI.ServiceReference.sexo pen8) {
            return base.Channel.agregar_sexoAsync(pen8);
        }
        
        public Diseño_UI.ServiceReference.sexo[] mostrar_sexo() {
            return base.Channel.mostrar_sexo();
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.sexo[]> mostrar_sexoAsync() {
            return base.Channel.mostrar_sexoAsync();
        }
        
        public int agregar_cargo(Diseño_UI.ServiceReference.cargo pen9) {
            return base.Channel.agregar_cargo(pen9);
        }
        
        public System.Threading.Tasks.Task<int> agregar_cargoAsync(Diseño_UI.ServiceReference.cargo pen9) {
            return base.Channel.agregar_cargoAsync(pen9);
        }
        
        public Diseño_UI.ServiceReference.cargo[] mostrar_cargo() {
            return base.Channel.mostrar_cargo();
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.cargo[]> mostrar_cargoAsync() {
            return base.Channel.mostrar_cargoAsync();
        }
        
        public int agregar_empleado(Diseño_UI.ServiceReference.Empleado pen10) {
            return base.Channel.agregar_empleado(pen10);
        }
        
        public System.Threading.Tasks.Task<int> agregar_empleadoAsync(Diseño_UI.ServiceReference.Empleado pen10) {
            return base.Channel.agregar_empleadoAsync(pen10);
        }
        
        public int actualizar_empleado(Diseño_UI.ServiceReference.Empleado pen10) {
            return base.Channel.actualizar_empleado(pen10);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_empleadoAsync(Diseño_UI.ServiceReference.Empleado pen10) {
            return base.Channel.actualizar_empleadoAsync(pen10);
        }
        
        public int eliminar_empleado(Diseño_UI.ServiceReference.Empleado pen10) {
            return base.Channel.eliminar_empleado(pen10);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_empleadoAsync(Diseño_UI.ServiceReference.Empleado pen10) {
            return base.Channel.eliminar_empleadoAsync(pen10);
        }
        
        public Diseño_UI.ServiceReference.Empleado[] mostrar_empleado() {
            return base.Channel.mostrar_empleado();
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.Empleado[]> mostrar_empleadoAsync() {
            return base.Channel.mostrar_empleadoAsync();
        }
        
        public int validar_empleado(Diseño_UI.ServiceReference.Empleado pen10) {
            return base.Channel.validar_empleado(pen10);
        }
        
        public System.Threading.Tasks.Task<int> validar_empleadoAsync(Diseño_UI.ServiceReference.Empleado pen10) {
            return base.Channel.validar_empleadoAsync(pen10);
        }
        
        public int agregar_ventas(Diseño_UI.ServiceReference.ventas pen11) {
            return base.Channel.agregar_ventas(pen11);
        }
        
        public System.Threading.Tasks.Task<int> agregar_ventasAsync(Diseño_UI.ServiceReference.ventas pen11) {
            return base.Channel.agregar_ventasAsync(pen11);
        }
        
        public Diseño_UI.ServiceReference.ventas[] mostrar_ventas() {
            return base.Channel.mostrar_ventas();
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.ventas[]> mostrar_ventasAsync() {
            return base.Channel.mostrar_ventasAsync();
        }
        
        public Diseño_UI.ServiceReference.ventas[] buscar_ventas(Diseño_UI.ServiceReference.ventas pen11) {
            return base.Channel.buscar_ventas(pen11);
        }
        
        public System.Threading.Tasks.Task<Diseño_UI.ServiceReference.ventas[]> buscar_ventasAsync(Diseño_UI.ServiceReference.ventas pen11) {
            return base.Channel.buscar_ventasAsync(pen11);
        }
    }
}
